const TIER_LIMITS = {
  free: {
    maxStacks: 1,
    maxLayersPerStack: 3,
    maxSavedDesigns: 1,
    maxCustomMaterials: 0,
    allowedAngles: [0],
    allowedDisplayModes: ['reflectivity', 'transmission'],
    allowedIlluminants: ['D65'],
    designAssistant: false,           // No optimizer access on free tier
    designAssistantMaxLayers: 0,
    reverseEngineer: false,
    colorTargetMode: false,
    csvUpload: false,
    recipeTracking: false,
    maxTrackingRuns: 0,
    yieldCalculator: false,
    maxMonteCarloIterations: 0,
    yieldColorSimulation: false,
    layerSensitivity: false,
    iad: false,
    maxMachines: 0,
    trackingDesignOverlay: false,
    trackingToleranceBands: false,
    trackingColorDrift: false,
    trackingTrendView: false,
    trackingExportPng: false,
    trackingExportCsv: true,
    trackingRunComparison: false,
    teamCollaboration: false,
    maxTeams: 0,
    maxTeamSeats: 0,
    aiChat: false,
    maxChatMessagesPerDay: 0,
    coatingTemplates: false,           // No templates on free tier
  },
  starter: {
    maxStacks: 3,
    maxLayersPerStack: 15,
    maxSavedDesigns: 25,
    maxCustomMaterials: 5,
    allowedAngles: [0, 15, 30, 45, 60],
    allowedDisplayModes: ['reflectivity', 'transmission', 'absorption'],
    allowedIlluminants: ['D65', 'D50', 'A', 'F2', 'F11'],
    designAssistant: 'target',
    designAssistantMaxLayers: 15,
    reverseEngineer: false,
    colorTargetMode: false,
    csvUpload: false,
    recipeTracking: true,
    maxTrackingRuns: 25,
    yieldCalculator: true,
    maxMonteCarloIterations: 1000,
    yieldColorSimulation: false,
    layerSensitivity: false,
    iad: false,
    maxMachines: 0,
    trackingDesignOverlay: true,
    trackingToleranceBands: false,
    trackingColorDrift: false,
    trackingTrendView: true,
    trackingExportPng: true,
    trackingExportCsv: true,
    trackingRunComparison: false,
    teamCollaboration: false,
    maxTeams: 0,
    maxTeamSeats: 0,
    aiChat: false,
    maxChatMessagesPerDay: 0,
    coatingTemplates: 'all',
  },
  professional: {
    maxStacks: -1,
    maxLayersPerStack: 50,
    maxSavedDesigns: -1,
    maxCustomMaterials: -1,
    allowedAngles: [0, 15, 30, 45, 60],
    allowedDisplayModes: ['reflectivity', 'transmission', 'absorption', 'admittance', 'efield', 'phaseShift'],
    allowedIlluminants: ['D65', 'D50', 'A', 'F2', 'F11'],
    designAssistant: 'all',
    designAssistantMaxLayers: 50,
    reverseEngineer: true,
    colorTargetMode: true,
    csvUpload: true,
    recipeTracking: true,
    maxTrackingRuns: -1,
    yieldCalculator: true,
    maxMonteCarloIterations: -1,
    yieldColorSimulation: true,
    layerSensitivity: true,
    iad: true,
    maxMachines: -1,
    trackingDesignOverlay: true,
    trackingToleranceBands: true,
    trackingColorDrift: true,
    trackingTrendView: true,
    trackingExportPng: true,
    trackingExportCsv: true,
    trackingRunComparison: true,
    teamCollaboration: false,
    maxTeams: 0,
    maxTeamSeats: 0,
    aiChat: 'full',
    maxChatMessagesPerDay: -1,
    coatingTemplates: 'all',
  },
  enterprise: {
    maxStacks: -1,
    maxLayersPerStack: 100,
    maxSavedDesigns: -1,
    maxCustomMaterials: -1,
    allowedAngles: [0, 15, 30, 45, 60],
    allowedDisplayModes: ['reflectivity', 'transmission', 'absorption', 'admittance', 'efield', 'phaseShift'],
    allowedIlluminants: ['D65', 'D50', 'A', 'F2', 'F11'],
    designAssistant: 'all',
    designAssistantMaxLayers: 100,
    reverseEngineer: true,
    colorTargetMode: true,
    csvUpload: true,
    recipeTracking: true,
    maxTrackingRuns: -1,
    yieldCalculator: true,
    maxMonteCarloIterations: -1,
    yieldColorSimulation: true,
    layerSensitivity: true,
    iad: true,
    maxMachines: -1,
    trackingDesignOverlay: true,
    trackingToleranceBands: true,
    trackingColorDrift: true,
    trackingTrendView: true,
    trackingExportPng: true,
    trackingExportCsv: true,
    trackingRunComparison: true,
    teamCollaboration: false,
    maxSeats: 5,                      // 5 seats included
    additionalSeatPrice: 49,          // +$49 per additional seat
    apiAccess: true,
    aiChat: 'full',
    maxChatMessagesPerDay: -1,
    coatingTemplates: 'all',
  },
};

// Price IDs mapped from env
const STRIPE_PRICES = {
  starter: {
    monthly: process.env.STRIPE_STARTER_MONTHLY_PRICE_ID,
    annual: process.env.STRIPE_STARTER_ANNUAL_PRICE_ID,
  },
  professional: {
    monthly: process.env.STRIPE_PROFESSIONAL_MONTHLY_PRICE_ID,
    annual: process.env.STRIPE_PROFESSIONAL_ANNUAL_PRICE_ID,
  },
  enterprise: {
    monthly: process.env.STRIPE_ENTERPRISE_MONTHLY_PRICE_ID,
    annual: process.env.STRIPE_ENTERPRISE_ANNUAL_PRICE_ID,
  },
  enterpriseSeat: {
    monthly: process.env.STRIPE_ENTERPRISE_SEAT_MONTHLY_PRICE_ID,
    annual: process.env.STRIPE_ENTERPRISE_SEAT_ANNUAL_PRICE_ID,
  },
};

module.exports = { TIER_LIMITS, STRIPE_PRICES };
